// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: application.proto

package application

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplicationFactory_Create_FullMethodName                    = "/application.ApplicationFactory/Create"
	ApplicationFactory_Delete_FullMethodName                    = "/application.ApplicationFactory/Delete"
	ApplicationFactory_Rebuild_FullMethodName                   = "/application.ApplicationFactory/Rebuild"
	ApplicationFactory_FetchLogs_FullMethodName                 = "/application.ApplicationFactory/FetchLogs"
	ApplicationFactory_Update_FullMethodName                    = "/application.ApplicationFactory/Update"
	ApplicationFactory_StartStoppedAppContainers_FullMethodName = "/application.ApplicationFactory/StartStoppedAppContainers"
	ApplicationFactory_StopAppContainers_FullMethodName         = "/application.ApplicationFactory/StopAppContainers"
	ApplicationFactory_DeleteAppContainers_FullMethodName       = "/application.ApplicationFactory/DeleteAppContainers"
)

// ApplicationFactoryClient is the client API for ApplicationFactory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationFactoryClient interface {
	Create(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (*ResponseBody, error)
	Delete(ctx context.Context, in *NameHolder, opts ...grpc.CallOption) (*DeletionResponse, error)
	Rebuild(ctx context.Context, in *NameHolder, opts ...grpc.CallOption) (*ResponseBody, error)
	FetchLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	Update(ctx context.Context, in *NameHolder, opts ...grpc.CallOption) (*ResponseBody, error)
	StartStoppedAppContainers(ctx context.Context, in *DownNodeRequestBody, opts ...grpc.CallOption) (*ContainerResponseBody, error)
	StopAppContainers(ctx context.Context, in *DownNodeRequestBody, opts ...grpc.CallOption) (*DeletionResponse, error)
	DeleteAppContainers(ctx context.Context, in *DownNodeRequestBody, opts ...grpc.CallOption) (*DeletionResponse, error)
}

type applicationFactoryClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationFactoryClient(cc grpc.ClientConnInterface) ApplicationFactoryClient {
	return &applicationFactoryClient{cc}
}

func (c *applicationFactoryClient) Create(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (*ResponseBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBody)
	err := c.cc.Invoke(ctx, ApplicationFactory_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) Delete(ctx context.Context, in *NameHolder, opts ...grpc.CallOption) (*DeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletionResponse)
	err := c.cc.Invoke(ctx, ApplicationFactory_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) Rebuild(ctx context.Context, in *NameHolder, opts ...grpc.CallOption) (*ResponseBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBody)
	err := c.cc.Invoke(ctx, ApplicationFactory_Rebuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) FetchLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, ApplicationFactory_FetchLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) Update(ctx context.Context, in *NameHolder, opts ...grpc.CallOption) (*ResponseBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBody)
	err := c.cc.Invoke(ctx, ApplicationFactory_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) StartStoppedAppContainers(ctx context.Context, in *DownNodeRequestBody, opts ...grpc.CallOption) (*ContainerResponseBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerResponseBody)
	err := c.cc.Invoke(ctx, ApplicationFactory_StartStoppedAppContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) StopAppContainers(ctx context.Context, in *DownNodeRequestBody, opts ...grpc.CallOption) (*DeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletionResponse)
	err := c.cc.Invoke(ctx, ApplicationFactory_StopAppContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationFactoryClient) DeleteAppContainers(ctx context.Context, in *DownNodeRequestBody, opts ...grpc.CallOption) (*DeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletionResponse)
	err := c.cc.Invoke(ctx, ApplicationFactory_DeleteAppContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationFactoryServer is the server API for ApplicationFactory service.
// All implementations must embed UnimplementedApplicationFactoryServer
// for forward compatibility.
type ApplicationFactoryServer interface {
	Create(context.Context, *RequestBody) (*ResponseBody, error)
	Delete(context.Context, *NameHolder) (*DeletionResponse, error)
	Rebuild(context.Context, *NameHolder) (*ResponseBody, error)
	FetchLogs(context.Context, *LogRequest) (*LogResponse, error)
	Update(context.Context, *NameHolder) (*ResponseBody, error)
	StartStoppedAppContainers(context.Context, *DownNodeRequestBody) (*ContainerResponseBody, error)
	StopAppContainers(context.Context, *DownNodeRequestBody) (*DeletionResponse, error)
	DeleteAppContainers(context.Context, *DownNodeRequestBody) (*DeletionResponse, error)
	mustEmbedUnimplementedApplicationFactoryServer()
}

// UnimplementedApplicationFactoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationFactoryServer struct{}

func (UnimplementedApplicationFactoryServer) Create(context.Context, *RequestBody) (*ResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedApplicationFactoryServer) Delete(context.Context, *NameHolder) (*DeletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedApplicationFactoryServer) Rebuild(context.Context, *NameHolder) (*ResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rebuild not implemented")
}
func (UnimplementedApplicationFactoryServer) FetchLogs(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchLogs not implemented")
}
func (UnimplementedApplicationFactoryServer) Update(context.Context, *NameHolder) (*ResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedApplicationFactoryServer) StartStoppedAppContainers(context.Context, *DownNodeRequestBody) (*ContainerResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStoppedAppContainers not implemented")
}
func (UnimplementedApplicationFactoryServer) StopAppContainers(context.Context, *DownNodeRequestBody) (*DeletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAppContainers not implemented")
}
func (UnimplementedApplicationFactoryServer) DeleteAppContainers(context.Context, *DownNodeRequestBody) (*DeletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAppContainers not implemented")
}
func (UnimplementedApplicationFactoryServer) mustEmbedUnimplementedApplicationFactoryServer() {}
func (UnimplementedApplicationFactoryServer) testEmbeddedByValue()                            {}

// UnsafeApplicationFactoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationFactoryServer will
// result in compilation errors.
type UnsafeApplicationFactoryServer interface {
	mustEmbedUnimplementedApplicationFactoryServer()
}

func RegisterApplicationFactoryServer(s grpc.ServiceRegistrar, srv ApplicationFactoryServer) {
	// If the following call pancis, it indicates UnimplementedApplicationFactoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplicationFactory_ServiceDesc, srv)
}

func _ApplicationFactory_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).Create(ctx, req.(*RequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameHolder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).Delete(ctx, req.(*NameHolder))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_Rebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameHolder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).Rebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_Rebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).Rebuild(ctx, req.(*NameHolder))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_FetchLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).FetchLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_FetchLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).FetchLogs(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameHolder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).Update(ctx, req.(*NameHolder))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_StartStoppedAppContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownNodeRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).StartStoppedAppContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_StartStoppedAppContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).StartStoppedAppContainers(ctx, req.(*DownNodeRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_StopAppContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownNodeRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).StopAppContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_StopAppContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).StopAppContainers(ctx, req.(*DownNodeRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationFactory_DeleteAppContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownNodeRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationFactoryServer).DeleteAppContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationFactory_DeleteAppContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationFactoryServer).DeleteAppContainers(ctx, req.(*DownNodeRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationFactory_ServiceDesc is the grpc.ServiceDesc for ApplicationFactory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationFactory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "application.ApplicationFactory",
	HandlerType: (*ApplicationFactoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ApplicationFactory_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ApplicationFactory_Delete_Handler,
		},
		{
			MethodName: "Rebuild",
			Handler:    _ApplicationFactory_Rebuild_Handler,
		},
		{
			MethodName: "FetchLogs",
			Handler:    _ApplicationFactory_FetchLogs_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ApplicationFactory_Update_Handler,
		},
		{
			MethodName: "StartStoppedAppContainers",
			Handler:    _ApplicationFactory_StartStoppedAppContainers_Handler,
		},
		{
			MethodName: "StopAppContainers",
			Handler:    _ApplicationFactory_StopAppContainers_Handler,
		},
		{
			MethodName: "DeleteAppContainers",
			Handler:    _ApplicationFactory_DeleteAppContainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}
