// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: application.proto

package application

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBody) Reset() {
	*x = RequestBody{}
	mi := &file_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBody) ProtoMessage() {}

func (x *RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBody.ProtoReflect.Descriptor instead.
func (*RequestBody) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{0}
}

func (x *RequestBody) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RequestBody) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RequestBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBody) Reset() {
	*x = ResponseBody{}
	mi := &file_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBody) ProtoMessage() {}

func (x *ResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBody.ProtoReflect.Descriptor instead.
func (*ResponseBody) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NameHolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameHolder) Reset() {
	*x = NameHolder{}
	mi := &file_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameHolder) ProtoMessage() {}

func (x *NameHolder) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameHolder.ProtoReflect.Descriptor instead.
func (*NameHolder) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{2}
}

func (x *NameHolder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionResponse) Reset() {
	*x = DeletionResponse{}
	mi := &file_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionResponse) ProtoMessage() {}

func (x *DeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionResponse.ProtoReflect.Descriptor instead.
func (*DeletionResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{3}
}

func (x *DeletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tail          string                 `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{4}
}

func (x *LogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogRequest) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          []string               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{5}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type NodeInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceURL   string                 `protobuf:"bytes,1,opt,name=instanceURL,proto3" json:"instanceURL,omitempty"`
	ContainerList []string               `protobuf:"bytes,2,rep,name=containerList,proto3" json:"containerList,omitempty"`
	DeleteVolume  bool                   `protobuf:"varint,3,opt,name=deleteVolume,proto3" json:"deleteVolume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInventory) Reset() {
	*x = NodeInventory{}
	mi := &file_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInventory) ProtoMessage() {}

func (x *NodeInventory) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInventory.ProtoReflect.Descriptor instead.
func (*NodeInventory) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInventory) GetInstanceURL() string {
	if x != nil {
		return x.InstanceURL
	}
	return ""
}

func (x *NodeInventory) GetContainerList() []string {
	if x != nil {
		return x.ContainerList
	}
	return nil
}

func (x *NodeInventory) GetDeleteVolume() bool {
	if x != nil {
		return x.DeleteVolume
	}
	return false
}

var File_application_proto protoreflect.FileDescriptor

const file_application_proto_rawDesc = "" +
	"\n" +
	"\x11application.proto\x12\vapplication\"S\n" +
	"\vRequestBody\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\"\n" +
	"\fResponseBody\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\" \n" +
	"\n" +
	"NameHolder\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10DeletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\n" +
	"LogRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\tR\x04tail\";\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x03(\tR\x04data\"{\n" +
	"\rNodeInventory\x12 \n" +
	"\vinstanceURL\x18\x01 \x01(\tR\vinstanceURL\x12$\n" +
	"\rcontainerList\x18\x02 \x03(\tR\rcontainerList\x12\"\n" +
	"\fdeleteVolume\x18\x03 \x01(\bR\fdeleteVolume2\x81\x04\n" +
	"\x12ApplicationFactory\x12?\n" +
	"\x06Create\x12\x18.application.RequestBody\x1a\x19.application.ResponseBody\"\x00\x12B\n" +
	"\x06Delete\x12\x17.application.NameHolder\x1a\x1d.application.DeletionResponse\"\x00\x12?\n" +
	"\aRebuild\x12\x17.application.NameHolder\x1a\x19.application.ResponseBody\"\x00\x12@\n" +
	"\tFetchLogs\x12\x17.application.LogRequest\x1a\x18.application.LogResponse\"\x00\x12>\n" +
	"\x06Update\x12\x17.application.NameHolder\x1a\x19.application.ResponseBody\"\x00\x12R\n" +
	"\x16FetchRunningContainers\x12\x1a.application.NodeInventory\x1a\x1a.application.NodeInventory\"\x00\x12O\n" +
	"\x10RemoveContainers\x12\x1a.application.NodeInventory\x1a\x1d.application.DeletionResponse\"\x00B\x0fZ\r./applicationb\x06proto3"

var (
	file_application_proto_rawDescOnce sync.Once
	file_application_proto_rawDescData []byte
)

func file_application_proto_rawDescGZIP() []byte {
	file_application_proto_rawDescOnce.Do(func() {
		file_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)))
	})
	return file_application_proto_rawDescData
}

var file_application_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_application_proto_goTypes = []any{
	(*RequestBody)(nil),      // 0: application.RequestBody
	(*ResponseBody)(nil),     // 1: application.ResponseBody
	(*NameHolder)(nil),       // 2: application.NameHolder
	(*DeletionResponse)(nil), // 3: application.DeletionResponse
	(*LogRequest)(nil),       // 4: application.LogRequest
	(*LogResponse)(nil),      // 5: application.LogResponse
	(*NodeInventory)(nil),    // 6: application.NodeInventory
}
var file_application_proto_depIdxs = []int32{
	0, // 0: application.ApplicationFactory.Create:input_type -> application.RequestBody
	2, // 1: application.ApplicationFactory.Delete:input_type -> application.NameHolder
	2, // 2: application.ApplicationFactory.Rebuild:input_type -> application.NameHolder
	4, // 3: application.ApplicationFactory.FetchLogs:input_type -> application.LogRequest
	2, // 4: application.ApplicationFactory.Update:input_type -> application.NameHolder
	6, // 5: application.ApplicationFactory.FetchRunningContainers:input_type -> application.NodeInventory
	6, // 6: application.ApplicationFactory.RemoveContainers:input_type -> application.NodeInventory
	1, // 7: application.ApplicationFactory.Create:output_type -> application.ResponseBody
	3, // 8: application.ApplicationFactory.Delete:output_type -> application.DeletionResponse
	1, // 9: application.ApplicationFactory.Rebuild:output_type -> application.ResponseBody
	5, // 10: application.ApplicationFactory.FetchLogs:output_type -> application.LogResponse
	1, // 11: application.ApplicationFactory.Update:output_type -> application.ResponseBody
	6, // 12: application.ApplicationFactory.FetchRunningContainers:output_type -> application.NodeInventory
	3, // 13: application.ApplicationFactory.RemoveContainers:output_type -> application.DeletionResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_application_proto_init() }
func file_application_proto_init() {
	if File_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_proto_goTypes,
		DependencyIndexes: file_application_proto_depIdxs,
		MessageInfos:      file_application_proto_msgTypes,
	}.Build()
	File_application_proto = out.File
	file_application_proto_goTypes = nil
	file_application_proto_depIdxs = nil
}
